version: '3'
services:
  database:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_BANKING_NAME}      
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT_INTERNAL}
      
  # mailer service settup later (recomment use gRPC)

  # another service
    