version: '3'
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'Internet_Banking'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - ${DB_PORT}:${DB_PORT_INTERNAL}
    expose:
      # Opens port 3306 on the container
      - ${DB_PORT}
      # Where our data will be persisted
    volumes:
      - db_file:/var/lib/mysql
volumes:
  db_file:
  # mailer service settup later (recomment use gRPC)

  # another service
    