export const LOGIN = 'USER_LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const REGISTER_LOADING = 'USER_REGISTER';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_DEAULFT = 'REGISTER_DEAULFT';

export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const BANKING_INFO_LOADING = 'BANKING_INFO_LOADING';
export const BANKING_INFO_FAILED = 'BANKING_INFO_FAILED';
export const BANKING_INFO_SUCCESS = 'BANKING_INFO_SUCCESS';

export const HISTORY_SUCCESS = 'HISTORY_SUCCESS';
export const HISTORY_LOADING = 'HISTORY_LOADING';
export const HISTORY_FAILED = 'HISTORY_FAILED';

export const ALL_ACCOUNT_SUCCESS = 'ALL_ACCOUNT_SUCCESS';
export const ALL_ACCOUNT_LOADING = 'ALL_ACCOUNT_LOADING';
export const ALL_ACCOUNT_FAILED = 'ALL_ACCOUNT_FAILED';

export const DEBT_SUCCESS = 'DEBT_SUCCESS';
export const DEBT_LOADING = 'DEBT_LOADING';
export const DEBT_FAILED = 'DEBT_FAILED';

export const NAME_REMINISCENT_SUCCESS = 'NAME_REMINISCENT_SUCCESS';
export const NAME_REMINISCENT_LOADING = 'NAME_REMINISCENT_LOADING';
export const NAME_REMINISCENT_FAILED = 'NAME_REMINISCENT_FAILED';
export const NAME_REMINISCENT_DELETED = 'NAME_REMINISCENT_DELETED';
export const NAME_REMINISCENT_EDIT = 'NAME_REMINISCENT_EDIT';

export const TRANSFER_MONEY_SUCCESS = 'TRANSFER_MONEY_SUCCESS';
export const TRANSFER_MONEY_LOADING = 'TRANSFER_MONEY_LOADING';
export const TRANSFER_MONEY_FAILED = 'TRANSFER_MONEY_FAILED';
