export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_AUTH_FAILED = 'LOGIN_AUTH_FAILED';
export const LOGIN_AUTH_SUCCESS = 'LOGIN_AUTH_SUCCESS';

export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_CUSTOMER = "AUTH_CUSTOMER";
export const AUTH_EMPLOYEE = "AUTH_EMPLOYEE";
export const AUTH_ADMIN = "AUTH_ADMIN";

export const REGISTER_LOADING = 'USER_REGISTER';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_DEFAULT = 'REGISTER_DEFAULT';

export const ACTIVE_ACCOUNT_LOADING = 'ACTIVE_ACCOUNT_LOADING';
export const ACTIVE_ACCOUNT_FAILED = 'ACTIVE_ACCOUNT_FAILED';
export const ACTIVE_ACCOUNT_SUCCESS = 'ACTIVE_ACCOUNT_SUCCESS';

export const CHANGE_PASSWORD_LOADING = 'CHANGE_PASSWORD_LOADING';
export const CHANGE_PASSWORD_FAILED = 'CHANGE_PASSWORD_FAILED';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';

export const VERIFY_FORGET_LOADING = 'VERIFY_FORGET_LOADING';
export const VERIFY_FORGET_FAILED = 'VERIFY_FORGET_FAILED';
export const VERIFY_FORGET_SUCCESS = 'VERIFY_FORGET_SUCCESS';

export const VERIFY_PASSWORD_LOADING = 'VERIFY_PASSWORD_LOADING';
export const VERIFY_PASSWORD_FAILED = 'VERIFY_PASSWORD_FAILED';
export const VERIFY_PASSWORD_SUCCESS = 'VERIFY_PASSWORD_SUCCESS';

export const BANKING_INFO_LOADING = 'BANKING_INFO_LOADING';
export const BANKING_INFO_FAILED = 'BANKING_INFO_FAILED';
export const BANKING_INFO_SUCCESS = 'BANKING_INFO_SUCCESS';

export const HISTORY_USER_TRANS_SUCCESS = 'HISTORY_USER_TRANS_SUCCESS';
export const HISTORY_USER_TRANS_LOADING = 'HISTORY_USER_TRANS_LOADING';
export const HISTORY_USER_TRANS_FAILED = 'HISTORY_USER_TRANS_FAILED';

export const HISTORY_TRANS_LOADING = 'HISTORY_TRANS_LOADING';
export const HISTORY_TRANS_SUCCESS = 'HISTORY_TRANS_SUCCESS';
export const HISTORY_TRANS_FAILED = 'HISTORY_TRANS_FAILED';

export const ALL_ACCOUNT_SUCCESS = 'ALL_ACCOUNT_SUCCESS';
export const ALL_ACCOUNT_LOADING = 'ALL_ACCOUNT_LOADING';
export const ALL_ACCOUNT_FAILED = 'ALL_ACCOUNT_FAILED';

export const PAYMENT_ACCOUNT_SUCCESS = 'PAYMENT_ACCOUNT_SUCCESS';
export const PAYMENT_ACCOUNT_LOADING = 'PAYMENT_ACCOUNT_LOADING';
export const PAYMENT_ACCOUNT_FAILED = 'PAYMENT_ACCOUNT_FAILED';

export const EMPLOYEE_LOADING = 'EMPLOYEE_LOADING';
export const EMPLOYEE_FAILED = 'EMPLOYEE_FAILED';
export const LOAD_EMPLOYEE_SUCCESS = 'LOAD_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const DELETE_EMPLOYEE_SUCCESS = 'DELETE_EMPLOYEE_SUCCESS';


export const REMIND_SUCCESS = 'REMIND_SUCCESS';
export const REMIND_LOADING = 'REMIND_LOADING';
export const REMIND_FAILED = 'REMIND_FAILED';

export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS';
export const NOTIFY_LOADING = 'NOTIFY_LOADING';
export const NOTIFY_DELETED = 'NOTIFY_DELETED';
export const NOTIFY_FAILED = 'NOTIFY_FAILED';

export const REMIND_DETAIL_SUCCESS = 'REMIND_DETAILL_SUCCESS';
export const REMIND_DETAIL_LOADING = 'REMIND_DETAILL_LOADING';
export const REMIND_DETAIL_FAILED = 'REMIND_DETAILL_FAILED';

export const DEBT_SUCCESS = 'DEBT_SUCCESS';
export const DEBT_LOADING = 'DEBT_LOADING';
export const DEBT_FAILED = 'DEBT_FAILED';
export const CREATE_DEBT_SUCCESS = 'CREATE_DEBT_SUCCESS';
export const CREATE_DEBT_LOADING = 'CREATE_DEBT_LOADING';
export const CREATE_DEBT_FAILED = 'CREATE_DEBT_FAILED';
export const NAME_DEBT_EDIT = 'NAME_DEBT_EDIT';
export const NAME_DEBT_DELETED = 'NAME_DEBT_DELETED';
export const NAME_DEBT_LOADING = 'NAME_DEBT_LOADING';

export const INDEBT_SUCCESS = 'INDEBT_SUCCESS';
export const INDEBT_LOADING = 'INDEBT_LOADING';
export const INDEBT_FAILED = 'INDEBT_FAILED';
export const INDEBT_DELETED = 'INDEBT_DELETED';

export const CREATE_ALIAS_FETCH = 'CREATE_ALIAS_FETCH';
export const CREATE_ALIAS_CREATING = 'CREATE_ALIAS_CREATING';
export const CREATE_ALIAS_LOADING = 'CREATE_ALIAS_LOADING';
export const CREATE_ALIAS_FAILED = 'CREATE_ALIAS_FAILED';
export const CREATE_ALIAS_DELETED = 'CREATE_ALIAS_DELETED';
export const CREATE_ALIAS_EDIT = 'CREATE_ALIAS_EDIT';

export const TRANSFER_SUCCESS = 'TRANSFER_SUCCESS';
export const TRANSFER_LOADING = 'TRANSFER_LOADING';
export const TRANSFER_INVALID = 'TRANSFER_INVALID';
export const TRANSFER_FAILED = 'TRANSFER_FAILED';

export const ALL_RECEIVER_SUCESS = 'ALL_RECEIVER_SUCESS';
export const ALL_RECEIVER_LOADING = 'ALL_RECEIVER_LOADING';
export const ALL_RECEIVER_FAILED = 'ALL_RECEIVER_FAILED';

export const INTERBANK_ASSOCIATE_SUCCESS = 'INTERBANK_ASSOCIATE_SUCCESS';
export const INTERBANK_ASSOCIATE_LOADING = 'INTERBANK_ASSOCIATE_LOADING';
export const INTERBANK_ASSOCIATE_FAILED = 'INTERBANK_ASSOCIATE__FAILED';

export const RECEIVER_SAVED_LOADING = 'RECEIVER_SAVED_LOADING';
export const RECEIVER_SAVED_SUCCESS = 'RECEIVER_SAVED_SUCCESS';
export const RECEIVER_SAVED_FAILED = 'RECEIVER_SAVED_FAILED';

export const VERIFY_OTP_LOADING = 'VERIFY_OTP_LOADING';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_INVALID = 'VERIFY_OTP_INVALID';
export const VERIFY_OTP_FAILED = 'VERIFY_OTP_FAILED';

export const RECHARGE_LOADING = 'RECHARGE_LOADING';
export const RECHARGE_SUCCESS = 'RECHARGE_SUCCESS';
export const RECHARGE_FAILED = 'RECHARGE_FAILED';

export const CREATE_ACC_LOADING = 'CREATE_ACC_LOADING';
export const CREATE_ACC_SUCCESS = 'CREATE_ACC_SUCCESS';
export const CREATE_ACC_FAILED = 'CREATE_ACC_FAILED';

export const CREATE_PAYMENT_LOADING = 'CREATE_PAYMENT_LOADING';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAILED = 'CREATE_PAYMENT_FAILED';

export const CLOSE_PAYMENT_LOADING = 'CLOSE_PAYMENT_LOADING';
export const CLOSE_PAYMENT_SUCCESS = 'CLOSE_PAYMENT_SUCCESS';
export const CLOSE_PAYMENT_FAILED = 'CLOSE_PAYMENT_FAILED';

export const FORGET_PASSWORD_LOADING = 'FORGET_PASSWORD_LOADING';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILED = 'FORGET_PASSWORD_FAILED';

export const GET_ACC_NAME_LOADING = 'GET_ACC_NAME_LOADING';
export const GET_ACC_NAME_SUCCESS = 'GET_ACC_NAME_SUCCESS';
export const GET_ACC_NAME_FAILED = 'GET_ACC_NAME_FAILED';